package controller;

import javafx.fxml.FXML;import javafx.scene.control.*;import javafx.scene.layout.*;import javafx.scene.Node;import service.*;import java.util.*;
public abstract class BaseLevelController {
 @FXML protected Label title,objective,instruction,feedback,scoreLabel,livesLabel;@FXML protected FlowPane challenge;@FXML protected VBox missionBox,quizBox;@FXML protected Label question;@FXML protected VBox choices;@FXML protected Button continueButton;
 private boolean missionComplete,answered;
 protected abstract int level(); protected abstract String titleText();protected abstract String objectiveText();protected abstract String instructionText();protected abstract List<String> challengeItems();protected abstract List<Integer> correctOrder();protected abstract String quizPrompt();protected abstract List<String> quizChoices();protected abstract int quizCorrect();protected abstract String explanation();
 @FXML public void initialize(){title.setText("MISSION "+level()+"  •  "+titleText());objective.setText(objectiveText());instruction.setText(instructionText());refreshHud();missionBox.getChildren().remove(feedback);quizBox.getChildren().add(quizBox.getChildren().size()-1,feedback);missionBox.setVisible(false);missionBox.setManaged(false);quizBox.setVisible(true);quizBox.setManaged(true);buildQuiz();}
 private final List<Integer> selected=new ArrayList<>();private final List<Node> selectedNodes=new ArrayList<>();
 private void select(int index,Node node){if(missionComplete||selected.contains(index))return;selected.add(index);selectedNodes.add(node);node.getStyleClass().add("selected-piece");AnimationManager.pulse(node);if(selected.size()==correctOrder().size()){if(selected.equals(correctOrder())){missionComplete=true;feedback.setText("Experiment successful! Scientific checkpoint unlocked.");feedback.getStyleClass().add("success");quizBox.setVisible(true);quizBox.setManaged(true);}else{feedback.setText("That arrangement is unstable. Try the scientific order again.");selectedNodes.forEach(AnimationManager::shake);selectedNodes.forEach(n->n.getStyleClass().remove("selected-piece"));selected.clear();selectedNodes.clear();AudioManager.play("wrong");}}}
 private void buildQuiz(){question.setText(quizPrompt());List<String> list=quizChoices();for(int i=0;i<list.size();i++){Button b=new Button(list.get(i));b.getStyleClass().add("answer-button");b.setMaxWidth(Double.MAX_VALUE);final int answer=i;b.setOnAction(e->answer(answer,b));choices.getChildren().add(b);}}
 private void answer(int answer,Button source){if(answered)return;answered=true;boolean correct=answer==quizCorrect();GameManager.getInstance().recordAnswer(correct);feedback.setText((correct?"Correct! ":"Not quite. ")+explanation());feedback.getStyleClass().add(correct?"success":"warning");if(correct)AnimationManager.pulse(source);else AnimationManager.shake(source);continueButton.setVisible(true);continueButton.setManaged(true);refreshHud();}
 @FXML private void proceed(){GameManager.getInstance().completeLevel(level());AudioManager.play("crystal");if(level()<6)SceneManager.switchScene("Level"+(level()+1)+".fxml");else SceneManager.switchScene("FinalQuiz.fxml");}
 @FXML private void menu(){SceneManager.switchScene("MainMenu.fxml");}private void refreshHud(){scoreLabel.setText("XP  "+GameManager.getInstance().getPlayer().getScore());livesLabel.setText("Lives  "+"♥".repeat(GameManager.getInstance().getPlayer().getLives()));}
}
